#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationsLink
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ALBOP")]
	public partial class OperationsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Add_Log(tbl_Add_Log instance);
    partial void Updatetbl_Add_Log(tbl_Add_Log instance);
    partial void Deletetbl_Add_Log(tbl_Add_Log instance);
    partial void Inserttbl_lkp_subobj(tbl_lkp_subobj instance);
    partial void Updatetbl_lkp_subobj(tbl_lkp_subobj instance);
    partial void Deletetbl_lkp_subobj(tbl_lkp_subobj instance);
    partial void InsertTbl_Login(Tbl_Login instance);
    partial void UpdateTbl_Login(Tbl_Login instance);
    partial void DeleteTbl_Login(Tbl_Login instance);
    partial void Inserttbl_lkp_data(tbl_lkp_data instance);
    partial void Updatetbl_lkp_data(tbl_lkp_data instance);
    partial void Deletetbl_lkp_data(tbl_lkp_data instance);
    #endregion
		
		public OperationsDataContext() : 
				base(global::System.Configuration.ConfigurationSettings.AppSettings["Licensing_Con"].ToString(), mappingSource)
		{
			OnCreated();
		}
		
		public OperationsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperationsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperationsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperationsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Add_Log> tbl_Add_Logs
		{
			get
			{
				return this.GetTable<tbl_Add_Log>();
			}
		}
		
		public System.Data.Linq.Table<tbl_lkp_subobj> tbl_lkp_subobjs
		{
			get
			{
				return this.GetTable<tbl_lkp_subobj>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Login> Tbl_Logins
		{
			get
			{
				return this.GetTable<Tbl_Login>();
			}
		}
		
		public System.Data.Linq.Table<tbl_lkp_data> tbl_lkp_datas
		{
			get
			{
				return this.GetTable<tbl_lkp_data>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Usp_Operations_getData")]
		public ISingleResult<Usp_Operations_getDataResult> Usp_Operations_getData()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Usp_Operations_getDataResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Usp_Operations_get_addlog")]
		public ISingleResult<Usp_Operations_get_addlogResult> Usp_Operations_get_addlog([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fromdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string frwd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string mailclerk, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string walkin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SSN", DbType="VarChar(50)")] string sSN, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string check)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), date, fromdate, frwd, mailclerk, walkin, sSN, check);
			return ((ISingleResult<Usp_Operations_get_addlogResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_GetBalanceAmountInChecks")]
		public ISingleResult<USP_GetBalanceAmountInChecksResult> USP_GetBalanceAmountInChecks([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string checkno)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), checkno);
			return ((ISingleResult<USP_GetBalanceAmountInChecksResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_OperationsAddlog")]
		public ISingleResult<USP_OperationsAddlogResult> USP_OperationsAddlog([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> flag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Add_log_ID", DbType="Int")] System.Nullable<int> add_log_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Date_Received", DbType="VarChar(50)")] string date_Received, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="From_Received", DbType="VarChar(50)")] string from_Received, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SSN", DbType="VarChar(50)")] string sSN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Forward_To", DbType="VarChar(50)")] string forward_To, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MailClerk", DbType="VarChar(50)")] string mailClerk, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpecialEntries", DbType="VarChar(MAX)")] string specialEntries, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentType", DbType="VarChar(50)")] string paymentType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="VarChar(50)")] string amount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CheckNumber", DbType="VarChar(50)")] string checkNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Walkin", DbType="VarChar(50)")] string walkin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Feetype", DbType="VarChar(50)")] string feetype, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(500)")] string uname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), flag, add_log_ID, date_Received, from_Received, sSN, forward_To, mailClerk, specialEntries, paymentType, amount, checkNumber, walkin, feetype, uname);
			return ((ISingleResult<USP_OperationsAddlogResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_getloghistory")]
		public ISingleResult<USP_getloghistoryResult> USP_getloghistory([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string addlofid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), addlofid);
			return ((ISingleResult<USP_getloghistoryResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Add_Log")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class tbl_Add_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Add_log_ID;
		
		private System.Nullable<System.DateTime> _Date_Received;
		
		private string _From_Received;
		
		private string _SSN;
		
		private string _Forward_To;
		
		private string _MailClerk;
		
		private string _SpecialEntries;
		
		private string _PaymentType;
		
		private System.Nullable<decimal> _Amount;
		
		private string _CheckNumber;
		
		private string _Walkin;
		
		private string _Feetype;
		
		private string _ReceiptNum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdd_log_IDChanging(int value);
    partial void OnAdd_log_IDChanged();
    partial void OnDate_ReceivedChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_ReceivedChanged();
    partial void OnFrom_ReceivedChanging(string value);
    partial void OnFrom_ReceivedChanged();
    partial void OnSSNChanging(string value);
    partial void OnSSNChanged();
    partial void OnForward_ToChanging(string value);
    partial void OnForward_ToChanged();
    partial void OnMailClerkChanging(string value);
    partial void OnMailClerkChanged();
    partial void OnSpecialEntriesChanging(string value);
    partial void OnSpecialEntriesChanged();
    partial void OnPaymentTypeChanging(string value);
    partial void OnPaymentTypeChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnCheckNumberChanging(string value);
    partial void OnCheckNumberChanged();
    partial void OnWalkinChanging(string value);
    partial void OnWalkinChanged();
    partial void OnFeetypeChanging(string value);
    partial void OnFeetypeChanged();
    partial void OnReceiptNumChanging(string value);
    partial void OnReceiptNumChanged();
    #endregion
		
		public tbl_Add_Log()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add_log_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int Add_log_ID
		{
			get
			{
				return this._Add_log_ID;
			}
			set
			{
				if ((this._Add_log_ID != value))
				{
					this.OnAdd_log_IDChanging(value);
					this.SendPropertyChanging();
					this._Add_log_ID = value;
					this.SendPropertyChanged("Add_log_ID");
					this.OnAdd_log_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Received", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<System.DateTime> Date_Received
		{
			get
			{
				return this._Date_Received;
			}
			set
			{
				if ((this._Date_Received != value))
				{
					this.OnDate_ReceivedChanging(value);
					this.SendPropertyChanging();
					this._Date_Received = value;
					this.SendPropertyChanged("Date_Received");
					this.OnDate_ReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Received", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string From_Received
		{
			get
			{
				return this._From_Received;
			}
			set
			{
				if ((this._From_Received != value))
				{
					this.OnFrom_ReceivedChanging(value);
					this.SendPropertyChanging();
					this._From_Received = value;
					this.SendPropertyChanged("From_Received");
					this.OnFrom_ReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this.OnSSNChanging(value);
					this.SendPropertyChanging();
					this._SSN = value;
					this.SendPropertyChanged("SSN");
					this.OnSSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Forward_To", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string Forward_To
		{
			get
			{
				return this._Forward_To;
			}
			set
			{
				if ((this._Forward_To != value))
				{
					this.OnForward_ToChanging(value);
					this.SendPropertyChanging();
					this._Forward_To = value;
					this.SendPropertyChanged("Forward_To");
					this.OnForward_ToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailClerk", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string MailClerk
		{
			get
			{
				return this._MailClerk;
			}
			set
			{
				if ((this._MailClerk != value))
				{
					this.OnMailClerkChanging(value);
					this.SendPropertyChanging();
					this._MailClerk = value;
					this.SendPropertyChanged("MailClerk");
					this.OnMailClerkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialEntries", DbType="VarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string SpecialEntries
		{
			get
			{
				return this._SpecialEntries;
			}
			set
			{
				if ((this._SpecialEntries != value))
				{
					this.OnSpecialEntriesChanging(value);
					this.SendPropertyChanging();
					this._SpecialEntries = value;
					this.SendPropertyChanged("SpecialEntries");
					this.OnSpecialEntriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentType", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string PaymentType
		{
			get
			{
				return this._PaymentType;
			}
			set
			{
				if ((this._PaymentType != value))
				{
					this.OnPaymentTypeChanging(value);
					this.SendPropertyChanging();
					this._PaymentType = value;
					this.SendPropertyChanged("PaymentType");
					this.OnPaymentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckNumber", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string CheckNumber
		{
			get
			{
				return this._CheckNumber;
			}
			set
			{
				if ((this._CheckNumber != value))
				{
					this.OnCheckNumberChanging(value);
					this.SendPropertyChanging();
					this._CheckNumber = value;
					this.SendPropertyChanged("CheckNumber");
					this.OnCheckNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Walkin", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string Walkin
		{
			get
			{
				return this._Walkin;
			}
			set
			{
				if ((this._Walkin != value))
				{
					this.OnWalkinChanging(value);
					this.SendPropertyChanging();
					this._Walkin = value;
					this.SendPropertyChanged("Walkin");
					this.OnWalkinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Feetype", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string Feetype
		{
			get
			{
				return this._Feetype;
			}
			set
			{
				if ((this._Feetype != value))
				{
					this.OnFeetypeChanging(value);
					this.SendPropertyChanging();
					this._Feetype = value;
					this.SendPropertyChanged("Feetype");
					this.OnFeetypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptNum", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string ReceiptNum
		{
			get
			{
				return this._ReceiptNum;
			}
			set
			{
				if ((this._ReceiptNum != value))
				{
					this.OnReceiptNumChanging(value);
					this.SendPropertyChanging();
					this._ReceiptNum = value;
					this.SendPropertyChanged("ReceiptNum");
					this.OnReceiptNumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lkp_subobj")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class tbl_lkp_subobj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Subobj_Id;
		
		private System.Nullable<int> _Rev_obj_Id;
		
		private string _Subobj_code;
		
		private string _Description;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<bool> _iseditable;
		
		private System.Nullable<bool> _ispartial;
		
		private System.Nullable<System.DateTime> _Effectivedate;
		
		private System.Nullable<int> _modifiedby;
		
		private System.Nullable<System.DateTime> _modifieddate;
		
		private System.Nullable<int> _Create_User;
		
		private System.Nullable<System.DateTime> _Create_Date;
		
		private string _Full_Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubobj_IdChanging(int value);
    partial void OnSubobj_IdChanged();
    partial void OnRev_obj_IdChanging(System.Nullable<int> value);
    partial void OnRev_obj_IdChanged();
    partial void OnSubobj_codeChanging(string value);
    partial void OnSubobj_codeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OniseditableChanging(System.Nullable<bool> value);
    partial void OniseditableChanged();
    partial void OnispartialChanging(System.Nullable<bool> value);
    partial void OnispartialChanged();
    partial void OnEffectivedateChanging(System.Nullable<System.DateTime> value);
    partial void OnEffectivedateChanged();
    partial void OnmodifiedbyChanging(System.Nullable<int> value);
    partial void OnmodifiedbyChanged();
    partial void OnmodifieddateChanging(System.Nullable<System.DateTime> value);
    partial void OnmodifieddateChanged();
    partial void OnCreate_UserChanging(System.Nullable<int> value);
    partial void OnCreate_UserChanged();
    partial void OnCreate_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreate_DateChanged();
    partial void OnFull_DescriptionChanging(string value);
    partial void OnFull_DescriptionChanged();
    #endregion
		
		public tbl_lkp_subobj()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subobj_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int Subobj_Id
		{
			get
			{
				return this._Subobj_Id;
			}
			set
			{
				if ((this._Subobj_Id != value))
				{
					this.OnSubobj_IdChanging(value);
					this.SendPropertyChanging();
					this._Subobj_Id = value;
					this.SendPropertyChanged("Subobj_Id");
					this.OnSubobj_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rev_obj_Id", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<int> Rev_obj_Id
		{
			get
			{
				return this._Rev_obj_Id;
			}
			set
			{
				if ((this._Rev_obj_Id != value))
				{
					this.OnRev_obj_IdChanging(value);
					this.SendPropertyChanging();
					this._Rev_obj_Id = value;
					this.SendPropertyChanged("Rev_obj_Id");
					this.OnRev_obj_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subobj_code", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Subobj_code
		{
			get
			{
				return this._Subobj_code;
			}
			set
			{
				if ((this._Subobj_code != value))
				{
					this.OnSubobj_codeChanging(value);
					this.SendPropertyChanging();
					this._Subobj_code = value;
					this.SendPropertyChanged("Subobj_code");
					this.OnSubobj_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(250)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iseditable", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<bool> iseditable
		{
			get
			{
				return this._iseditable;
			}
			set
			{
				if ((this._iseditable != value))
				{
					this.OniseditableChanging(value);
					this.SendPropertyChanging();
					this._iseditable = value;
					this.SendPropertyChanged("iseditable");
					this.OniseditableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ispartial", DbType="Bit")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<bool> ispartial
		{
			get
			{
				return this._ispartial;
			}
			set
			{
				if ((this._ispartial != value))
				{
					this.OnispartialChanging(value);
					this.SendPropertyChanging();
					this._ispartial = value;
					this.SendPropertyChanged("ispartial");
					this.OnispartialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Effectivedate", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<System.DateTime> Effectivedate
		{
			get
			{
				return this._Effectivedate;
			}
			set
			{
				if ((this._Effectivedate != value))
				{
					this.OnEffectivedateChanging(value);
					this.SendPropertyChanging();
					this._Effectivedate = value;
					this.SendPropertyChanged("Effectivedate");
					this.OnEffectivedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifiedby", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<int> modifiedby
		{
			get
			{
				return this._modifiedby;
			}
			set
			{
				if ((this._modifiedby != value))
				{
					this.OnmodifiedbyChanging(value);
					this.SendPropertyChanging();
					this._modifiedby = value;
					this.SendPropertyChanged("modifiedby");
					this.OnmodifiedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifieddate", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<System.DateTime> modifieddate
		{
			get
			{
				return this._modifieddate;
			}
			set
			{
				if ((this._modifieddate != value))
				{
					this.OnmodifieddateChanging(value);
					this.SendPropertyChanging();
					this._modifieddate = value;
					this.SendPropertyChanged("modifieddate");
					this.OnmodifieddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_User", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<int> Create_User
		{
			get
			{
				return this._Create_User;
			}
			set
			{
				if ((this._Create_User != value))
				{
					this.OnCreate_UserChanging(value);
					this.SendPropertyChanging();
					this._Create_User = value;
					this.SendPropertyChanged("Create_User");
					this.OnCreate_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_Date", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public System.Nullable<System.DateTime> Create_Date
		{
			get
			{
				return this._Create_Date;
			}
			set
			{
				if ((this._Create_Date != value))
				{
					this.OnCreate_DateChanging(value);
					this.SendPropertyChanging();
					this._Create_Date = value;
					this.SendPropertyChanged("Create_Date");
					this.OnCreate_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_Description", DbType="VarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string Full_Description
		{
			get
			{
				return this._Full_Description;
			}
			set
			{
				if ((this._Full_Description != value))
				{
					this.OnFull_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._Full_Description = value;
					this.SendPropertyChanged("Full_Description");
					this.OnFull_DescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Login")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Tbl_Login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _loginID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _MiddleName;
		
		private string _Suffix;
		
		private string _isstatus;
		
		private string _isadmin;
		
		private string _Email;
		
		private string _UserName;
		
		private string _Password;
		
		private System.Nullable<System.DateTime> _ExpireDate;
		
		private string _LastLogin;
		
		private string _IsTemp;
		
		private System.Nullable<int> _UserType;
		
		private System.Nullable<int> _Modifyby;
		
		private System.Nullable<System.DateTime> _Modifydate;
		
		private System.Nullable<int> _Create_User;
		
		private System.Nullable<System.DateTime> _Create_Date;
		
		private System.Nullable<int> _Pagecount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnloginIDChanging(int value);
    partial void OnloginIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnSuffixChanging(string value);
    partial void OnSuffixChanged();
    partial void OnisstatusChanging(string value);
    partial void OnisstatusChanged();
    partial void OnisadminChanging(string value);
    partial void OnisadminChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnExpireDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpireDateChanged();
    partial void OnLastLoginChanging(string value);
    partial void OnLastLoginChanged();
    partial void OnIsTempChanging(string value);
    partial void OnIsTempChanged();
    partial void OnUserTypeChanging(System.Nullable<int> value);
    partial void OnUserTypeChanged();
    partial void OnModifybyChanging(System.Nullable<int> value);
    partial void OnModifybyChanged();
    partial void OnModifydateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifydateChanged();
    partial void OnCreate_UserChanging(System.Nullable<int> value);
    partial void OnCreate_UserChanged();
    partial void OnCreate_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreate_DateChanged();
    partial void OnPagecountChanging(System.Nullable<int> value);
    partial void OnPagecountChanged();
    #endregion
		
		public Tbl_Login()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loginID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int loginID
		{
			get
			{
				return this._loginID;
			}
			set
			{
				if ((this._loginID != value))
				{
					this.OnloginIDChanging(value);
					this.SendPropertyChanging();
					this._loginID = value;
					this.SendPropertyChanged("loginID");
					this.OnloginIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suffix", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string Suffix
		{
			get
			{
				return this._Suffix;
			}
			set
			{
				if ((this._Suffix != value))
				{
					this.OnSuffixChanging(value);
					this.SendPropertyChanging();
					this._Suffix = value;
					this.SendPropertyChanged("Suffix");
					this.OnSuffixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isstatus", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string isstatus
		{
			get
			{
				return this._isstatus;
			}
			set
			{
				if ((this._isstatus != value))
				{
					this.OnisstatusChanging(value);
					this.SendPropertyChanging();
					this._isstatus = value;
					this.SendPropertyChanged("isstatus");
					this.OnisstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isadmin", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string isadmin
		{
			get
			{
				return this._isadmin;
			}
			set
			{
				if ((this._isadmin != value))
				{
					this.OnisadminChanging(value);
					this.SendPropertyChanging();
					this._isadmin = value;
					this.SendPropertyChanged("isadmin");
					this.OnisadminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpireDate", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<System.DateTime> ExpireDate
		{
			get
			{
				return this._ExpireDate;
			}
			set
			{
				if ((this._ExpireDate != value))
				{
					this.OnExpireDateChanging(value);
					this.SendPropertyChanging();
					this._ExpireDate = value;
					this.SendPropertyChanged("ExpireDate");
					this.OnExpireDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLogin", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string LastLogin
		{
			get
			{
				return this._LastLogin;
			}
			set
			{
				if ((this._LastLogin != value))
				{
					this.OnLastLoginChanging(value);
					this.SendPropertyChanging();
					this._LastLogin = value;
					this.SendPropertyChanged("LastLogin");
					this.OnLastLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTemp", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public string IsTemp
		{
			get
			{
				return this._IsTemp;
			}
			set
			{
				if ((this._IsTemp != value))
				{
					this.OnIsTempChanging(value);
					this.SendPropertyChanging();
					this._IsTemp = value;
					this.SendPropertyChanged("IsTemp");
					this.OnIsTempChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public System.Nullable<int> UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modifyby", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public System.Nullable<int> Modifyby
		{
			get
			{
				return this._Modifyby;
			}
			set
			{
				if ((this._Modifyby != value))
				{
					this.OnModifybyChanging(value);
					this.SendPropertyChanging();
					this._Modifyby = value;
					this.SendPropertyChanged("Modifyby");
					this.OnModifybyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modifydate", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public System.Nullable<System.DateTime> Modifydate
		{
			get
			{
				return this._Modifydate;
			}
			set
			{
				if ((this._Modifydate != value))
				{
					this.OnModifydateChanging(value);
					this.SendPropertyChanging();
					this._Modifydate = value;
					this.SendPropertyChanged("Modifydate");
					this.OnModifydateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_User", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public System.Nullable<int> Create_User
		{
			get
			{
				return this._Create_User;
			}
			set
			{
				if ((this._Create_User != value))
				{
					this.OnCreate_UserChanging(value);
					this.SendPropertyChanging();
					this._Create_User = value;
					this.SendPropertyChanged("Create_User");
					this.OnCreate_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_Date", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public System.Nullable<System.DateTime> Create_Date
		{
			get
			{
				return this._Create_Date;
			}
			set
			{
				if ((this._Create_Date != value))
				{
					this.OnCreate_DateChanging(value);
					this.SendPropertyChanging();
					this._Create_Date = value;
					this.SendPropertyChanged("Create_Date");
					this.OnCreate_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pagecount", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public System.Nullable<int> Pagecount
		{
			get
			{
				return this._Pagecount;
			}
			set
			{
				if ((this._Pagecount != value))
				{
					this.OnPagecountChanging(value);
					this.SendPropertyChanging();
					this._Pagecount = value;
					this.SendPropertyChanged("Pagecount");
					this.OnPagecountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lkp_data")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class tbl_lkp_data : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Lkp_data_ID;
		
		private int _Lkp_tbl_ID;
		
		private int _Org_ID;
		
		private string _Values;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLkp_data_IDChanging(int value);
    partial void OnLkp_data_IDChanged();
    partial void OnLkp_tbl_IDChanging(int value);
    partial void OnLkp_tbl_IDChanged();
    partial void OnOrg_IDChanging(int value);
    partial void OnOrg_IDChanged();
    partial void OnValuesChanging(string value);
    partial void OnValuesChanged();
    #endregion
		
		public tbl_lkp_data()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lkp_data_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int Lkp_data_ID
		{
			get
			{
				return this._Lkp_data_ID;
			}
			set
			{
				if ((this._Lkp_data_ID != value))
				{
					this.OnLkp_data_IDChanging(value);
					this.SendPropertyChanging();
					this._Lkp_data_ID = value;
					this.SendPropertyChanged("Lkp_data_ID");
					this.OnLkp_data_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lkp_tbl_ID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public int Lkp_tbl_ID
		{
			get
			{
				return this._Lkp_tbl_ID;
			}
			set
			{
				if ((this._Lkp_tbl_ID != value))
				{
					this.OnLkp_tbl_IDChanging(value);
					this.SendPropertyChanging();
					this._Lkp_tbl_ID = value;
					this.SendPropertyChanged("Lkp_tbl_ID");
					this.OnLkp_tbl_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Org_ID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public int Org_ID
		{
			get
			{
				return this._Org_ID;
			}
			set
			{
				if ((this._Org_ID != value))
				{
					this.OnOrg_IDChanging(value);
					this.SendPropertyChanging();
					this._Org_ID = value;
					this.SendPropertyChanged("Org_ID");
					this.OnOrg_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Values]", Storage="_Values", DbType="VarChar(500)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string Values
		{
			get
			{
				return this._Values;
			}
			set
			{
				if ((this._Values != value))
				{
					this.OnValuesChanging(value);
					this.SendPropertyChanging();
					this._Values = value;
					this.SendPropertyChanged("Values");
					this.OnValuesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Usp_Operations_getDataResult
	{
		
		private int _Add_log_ID;
		
		private System.Nullable<System.DateTime> _Date_Received;
		
		private string _Description;
		
		private string _From_Received;
		
		private string _SSN;
		
		private string _Forward_To;
		
		private string _MailClerk;
		
		private string _SpecialEntries;
		
		private string _Payment_Type;
		
		private System.Nullable<decimal> _Amount;
		
		private string _CheckNumber;
		
		private string _Walkin;
		
		public Usp_Operations_getDataResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add_log_ID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int Add_log_ID
		{
			get
			{
				return this._Add_log_ID;
			}
			set
			{
				if ((this._Add_log_ID != value))
				{
					this._Add_log_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Received", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<System.DateTime> Date_Received
		{
			get
			{
				return this._Date_Received;
			}
			set
			{
				if ((this._Date_Received != value))
				{
					this._Date_Received = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(250)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Received", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string From_Received
		{
			get
			{
				return this._From_Received;
			}
			set
			{
				if ((this._From_Received != value))
				{
					this._From_Received = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this._SSN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Forward_To", DbType="VarChar(101) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string Forward_To
		{
			get
			{
				return this._Forward_To;
			}
			set
			{
				if ((this._Forward_To != value))
				{
					this._Forward_To = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailClerk", DbType="VarChar(101) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string MailClerk
		{
			get
			{
				return this._MailClerk;
			}
			set
			{
				if ((this._MailClerk != value))
				{
					this._MailClerk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialEntries", DbType="VarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string SpecialEntries
		{
			get
			{
				return this._SpecialEntries;
			}
			set
			{
				if ((this._SpecialEntries != value))
				{
					this._SpecialEntries = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_Type", DbType="VarChar(500)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string Payment_Type
		{
			get
			{
				return this._Payment_Type;
			}
			set
			{
				if ((this._Payment_Type != value))
				{
					this._Payment_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckNumber", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string CheckNumber
		{
			get
			{
				return this._CheckNumber;
			}
			set
			{
				if ((this._CheckNumber != value))
				{
					this._CheckNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Walkin", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string Walkin
		{
			get
			{
				return this._Walkin;
			}
			set
			{
				if ((this._Walkin != value))
				{
					this._Walkin = value;
				}
			}
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Usp_Operations_get_addlogResult
	{
		
		private int _Add_log_ID;
		
		private System.Nullable<System.DateTime> _Date_Received;
		
		private string _Description;
		
		private string _From_Received;
		
		private string _SSN;
		
		private string _Forward_To;
		
		private string _MailClerk;
		
		private string _SpecialEntries;
		
		private string _Payment_Type;
		
		private System.Nullable<decimal> _Amount;
		
		private string _CheckNumber;
		
		private string _Walkin;
		
		public Usp_Operations_get_addlogResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add_log_ID", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int Add_log_ID
		{
			get
			{
				return this._Add_log_ID;
			}
			set
			{
				if ((this._Add_log_ID != value))
				{
					this._Add_log_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Received", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<System.DateTime> Date_Received
		{
			get
			{
				return this._Date_Received;
			}
			set
			{
				if ((this._Date_Received != value))
				{
					this._Date_Received = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(250)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Received", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string From_Received
		{
			get
			{
				return this._From_Received;
			}
			set
			{
				if ((this._From_Received != value))
				{
					this._From_Received = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this._SSN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Forward_To", DbType="VarChar(152) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string Forward_To
		{
			get
			{
				return this._Forward_To;
			}
			set
			{
				if ((this._Forward_To != value))
				{
					this._Forward_To = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailClerk", DbType="VarChar(152) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string MailClerk
		{
			get
			{
				return this._MailClerk;
			}
			set
			{
				if ((this._MailClerk != value))
				{
					this._MailClerk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialEntries", DbType="VarChar(MAX)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string SpecialEntries
		{
			get
			{
				return this._SpecialEntries;
			}
			set
			{
				if ((this._SpecialEntries != value))
				{
					this._SpecialEntries = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_Type", DbType="VarChar(500)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string Payment_Type
		{
			get
			{
				return this._Payment_Type;
			}
			set
			{
				if ((this._Payment_Type != value))
				{
					this._Payment_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckNumber", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string CheckNumber
		{
			get
			{
				return this._CheckNumber;
			}
			set
			{
				if ((this._CheckNumber != value))
				{
					this._CheckNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Walkin", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public string Walkin
		{
			get
			{
				return this._Walkin;
			}
			set
			{
				if ((this._Walkin != value))
				{
					this._Walkin = value;
				}
			}
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class USP_GetBalanceAmountInChecksResult
	{
		
		private string _Checknum;
		
		private System.Nullable<decimal> _UsedAmount;
		
		private System.Nullable<decimal> _ActualAmount;
		
		private System.Nullable<decimal> _BalanceAmount;
		
		public USP_GetBalanceAmountInChecksResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checknum", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Checknum
		{
			get
			{
				return this._Checknum;
			}
			set
			{
				if ((this._Checknum != value))
				{
					this._Checknum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsedAmount", DbType="Decimal(38,2)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<decimal> UsedAmount
		{
			get
			{
				return this._UsedAmount;
			}
			set
			{
				if ((this._UsedAmount != value))
				{
					this._UsedAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualAmount", DbType="Decimal(18,2)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<decimal> ActualAmount
		{
			get
			{
				return this._ActualAmount;
			}
			set
			{
				if ((this._ActualAmount != value))
				{
					this._ActualAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalanceAmount", DbType="Decimal(38,2)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<decimal> BalanceAmount
		{
			get
			{
				return this._BalanceAmount;
			}
			set
			{
				if ((this._BalanceAmount != value))
				{
					this._BalanceAmount = value;
				}
			}
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class USP_OperationsAddlogResult
	{
		
		private System.Nullable<decimal> _Column1;
		
		public USP_OperationsAddlogResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Decimal(38,0)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public System.Nullable<decimal> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class USP_getloghistoryResult
	{
		
		private string _Old_Value;
		
		private string _New_Value;
		
		private string _changedby;
		
		private System.Nullable<System.DateTime> _changedon;
		
		public USP_getloghistoryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Old Value]", Storage="_Old_Value", DbType="VarChar(101) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Old_Value
		{
			get
			{
				return this._Old_Value;
			}
			set
			{
				if ((this._Old_Value != value))
				{
					this._Old_Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[New Value]", Storage="_New_Value", DbType="VarChar(101) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string New_Value
		{
			get
			{
				return this._New_Value;
			}
			set
			{
				if ((this._New_Value != value))
				{
					this._New_Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_changedby", DbType="VarChar(500)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string changedby
		{
			get
			{
				return this._changedby;
			}
			set
			{
				if ((this._changedby != value))
				{
					this._changedby = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_changedon", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<System.DateTime> changedon
		{
			get
			{
				return this._changedon;
			}
			set
			{
				if ((this._changedon != value))
				{
					this._changedon = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
