#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting_Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "ALBOP")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_lkp_subobj(tbl_lkp_subobj instance);
    partial void Updatetbl_lkp_subobj(tbl_lkp_subobj instance);
    partial void Deletetbl_lkp_subobj(tbl_lkp_subobj instance);
    partial void InsertTBL_Accounting_Consumer_InvoiceFee(TBL_Accounting_Consumer_InvoiceFee instance);
    partial void UpdateTBL_Accounting_Consumer_InvoiceFee(TBL_Accounting_Consumer_InvoiceFee instance);
    partial void DeleteTBL_Accounting_Consumer_InvoiceFee(TBL_Accounting_Consumer_InvoiceFee instance);
    partial void InsertTBL_Accounting_ConsumerInvoice(TBL_Accounting_ConsumerInvoice instance);
    partial void UpdateTBL_Accounting_ConsumerInvoice(TBL_Accounting_ConsumerInvoice instance);
    partial void DeleteTBL_Accounting_ConsumerInvoice(TBL_Accounting_ConsumerInvoice instance);
    partial void Inserttbl_lkp_data(tbl_lkp_data instance);
    partial void Updatetbl_lkp_data(tbl_lkp_data instance);
    partial void Deletetbl_lkp_data(tbl_lkp_data instance);
    #endregion
		
		public DataClasses1DataContext() :
        base(global::System.Configuration.ConfigurationSettings.AppSettings["Licensing_Con"].ToString(), mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_lkp_table> tbl_lkp_tables
		{
			get
			{
				return this.GetTable<tbl_lkp_table>();
			}
		}
		
		public System.Data.Linq.Table<tbl_lkp_subobj> tbl_lkp_subobjs
		{
			get
			{
				return this.GetTable<tbl_lkp_subobj>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Accounting_Consumer_InvoiceFee> TBL_Accounting_Consumer_InvoiceFees
		{
			get
			{
				return this.GetTable<TBL_Accounting_Consumer_InvoiceFee>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Accounting_ConsumerInvoice> TBL_Accounting_ConsumerInvoices
		{
			get
			{
				return this.GetTable<TBL_Accounting_ConsumerInvoice>();
			}
		}
		
		public System.Data.Linq.Table<tbl_lkp_data> tbl_lkp_datas
		{
			get
			{
				return this.GetTable<tbl_lkp_data>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_GetValues")]
		public int USP_GetValues([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string tname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string col_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(950)")] string cond)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tname, col_name, cond);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_Accounting_ConsumerInvoice")]
		public int USP_Accounting_ConsumerInvoice([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> flag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cons_Invoice_Id", DbType="Int")] System.Nullable<int> cons_Invoice_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="VarChar(50)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="VarChar(50)")] string address1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="VarChar(50)")] string address2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="VarChar(50)")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zip", DbType="VarChar(50)")] string zip, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> latid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Indicator", DbType="VarChar(50)")] string indicator)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), flag, cons_Invoice_Id, id, address1, address2, city, state, zip, latid, indicator);
			latid = ((System.Nullable<int>)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_Accounting_ConsumerInvoice_Fees")]
		public int USP_Accounting_ConsumerInvoice_Fees([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> flag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cons_Invoice_FeeId", DbType="Int")] System.Nullable<int> cons_Invoice_FeeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cons_Invoice_Id", DbType="Int")] System.Nullable<int> cons_Invoice_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FeeTypeId", DbType="VarChar(MAX)")] string feeTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="VarChar(50)")] string amount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DueDate", DbType="VarChar(50)")] string dueDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), flag, cons_Invoice_FeeId, cons_Invoice_Id, feeTypeId, amount, dueDate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_Accounting_GetFinancialBatchResults")]
		public ISingleResult<USP_Accounting_GetFinancialBatchResultsResult> USP_Accounting_GetFinancialBatchResults([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string batchno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string recno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string batstatus, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string createdfrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string createdto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, batchno, recno, batstatus, createdfrom, createdto);
			return ((ISingleResult<USP_Accounting_GetFinancialBatchResultsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_Accounting_GetFinancialBatchTransforBatchNoResults")]
		public ISingleResult<USP_Accounting_GetFinancialBatchTransforBatchNoResultsResult> USP_Accounting_GetFinancialBatchTransforBatchNoResults([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string batno)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), batno);
			return ((ISingleResult<USP_Accounting_GetFinancialBatchTransforBatchNoResultsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_consumerInvoicerpt")]
		public ISingleResult<usp_consumerInvoicerptResult> usp_consumerInvoicerpt([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string consumerinvioceid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), consumerinvioceid);
			return ((ISingleResult<usp_consumerInvoicerptResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lkp_tables")]
	public partial class tbl_lkp_table
	{
		
		private int _Lkp_tbl_ID;
		
		private string _Lkp_table_name;
		
		private int _Module_ID;
		
		public tbl_lkp_table()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lkp_tbl_ID", DbType="Int NOT NULL")]
		public int Lkp_tbl_ID
		{
			get
			{
				return this._Lkp_tbl_ID;
			}
			set
			{
				if ((this._Lkp_tbl_ID != value))
				{
					this._Lkp_tbl_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lkp_table_name", DbType="VarChar(50)")]
		public string Lkp_table_name
		{
			get
			{
				return this._Lkp_table_name;
			}
			set
			{
				if ((this._Lkp_table_name != value))
				{
					this._Lkp_table_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Module_ID", DbType="Int NOT NULL")]
		public int Module_ID
		{
			get
			{
				return this._Module_ID;
			}
			set
			{
				if ((this._Module_ID != value))
				{
					this._Module_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lkp_subobj")]
	public partial class tbl_lkp_subobj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Subobj_Id;
		
		private System.Nullable<int> _Rev_obj_Id;
		
		private string _Subobj_code;
		
		private string _Description;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<bool> _iseditable;
		
		private System.Nullable<bool> _ispartial;
		
		private System.Nullable<System.DateTime> _Effectivedate;
		
		private System.Nullable<int> _modifiedby;
		
		private System.Nullable<System.DateTime> _modifieddate;
		
		private System.Nullable<int> _Create_User;
		
		private System.Nullable<System.DateTime> _Create_Date;
		
		private string _Full_Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubobj_IdChanging(int value);
    partial void OnSubobj_IdChanged();
    partial void OnRev_obj_IdChanging(System.Nullable<int> value);
    partial void OnRev_obj_IdChanged();
    partial void OnSubobj_codeChanging(string value);
    partial void OnSubobj_codeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OniseditableChanging(System.Nullable<bool> value);
    partial void OniseditableChanged();
    partial void OnispartialChanging(System.Nullable<bool> value);
    partial void OnispartialChanged();
    partial void OnEffectivedateChanging(System.Nullable<System.DateTime> value);
    partial void OnEffectivedateChanged();
    partial void OnmodifiedbyChanging(System.Nullable<int> value);
    partial void OnmodifiedbyChanged();
    partial void OnmodifieddateChanging(System.Nullable<System.DateTime> value);
    partial void OnmodifieddateChanged();
    partial void OnCreate_UserChanging(System.Nullable<int> value);
    partial void OnCreate_UserChanged();
    partial void OnCreate_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreate_DateChanged();
    partial void OnFull_DescriptionChanging(string value);
    partial void OnFull_DescriptionChanged();
    #endregion
		
		public tbl_lkp_subobj()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subobj_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Subobj_Id
		{
			get
			{
				return this._Subobj_Id;
			}
			set
			{
				if ((this._Subobj_Id != value))
				{
					this.OnSubobj_IdChanging(value);
					this.SendPropertyChanging();
					this._Subobj_Id = value;
					this.SendPropertyChanged("Subobj_Id");
					this.OnSubobj_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rev_obj_Id", DbType="Int")]
		public System.Nullable<int> Rev_obj_Id
		{
			get
			{
				return this._Rev_obj_Id;
			}
			set
			{
				if ((this._Rev_obj_Id != value))
				{
					this.OnRev_obj_IdChanging(value);
					this.SendPropertyChanging();
					this._Rev_obj_Id = value;
					this.SendPropertyChanged("Rev_obj_Id");
					this.OnRev_obj_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subobj_code", DbType="VarChar(50)")]
		public string Subobj_code
		{
			get
			{
				return this._Subobj_code;
			}
			set
			{
				if ((this._Subobj_code != value))
				{
					this.OnSubobj_codeChanging(value);
					this.SendPropertyChanging();
					this._Subobj_code = value;
					this.SendPropertyChanged("Subobj_code");
					this.OnSubobj_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(250)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iseditable", DbType="Bit")]
		public System.Nullable<bool> iseditable
		{
			get
			{
				return this._iseditable;
			}
			set
			{
				if ((this._iseditable != value))
				{
					this.OniseditableChanging(value);
					this.SendPropertyChanging();
					this._iseditable = value;
					this.SendPropertyChanged("iseditable");
					this.OniseditableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ispartial", DbType="Bit")]
		public System.Nullable<bool> ispartial
		{
			get
			{
				return this._ispartial;
			}
			set
			{
				if ((this._ispartial != value))
				{
					this.OnispartialChanging(value);
					this.SendPropertyChanging();
					this._ispartial = value;
					this.SendPropertyChanged("ispartial");
					this.OnispartialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Effectivedate", DbType="DateTime")]
		public System.Nullable<System.DateTime> Effectivedate
		{
			get
			{
				return this._Effectivedate;
			}
			set
			{
				if ((this._Effectivedate != value))
				{
					this.OnEffectivedateChanging(value);
					this.SendPropertyChanging();
					this._Effectivedate = value;
					this.SendPropertyChanged("Effectivedate");
					this.OnEffectivedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifiedby", DbType="Int")]
		public System.Nullable<int> modifiedby
		{
			get
			{
				return this._modifiedby;
			}
			set
			{
				if ((this._modifiedby != value))
				{
					this.OnmodifiedbyChanging(value);
					this.SendPropertyChanging();
					this._modifiedby = value;
					this.SendPropertyChanged("modifiedby");
					this.OnmodifiedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifieddate", DbType="DateTime")]
		public System.Nullable<System.DateTime> modifieddate
		{
			get
			{
				return this._modifieddate;
			}
			set
			{
				if ((this._modifieddate != value))
				{
					this.OnmodifieddateChanging(value);
					this.SendPropertyChanging();
					this._modifieddate = value;
					this.SendPropertyChanged("modifieddate");
					this.OnmodifieddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_User", DbType="Int")]
		public System.Nullable<int> Create_User
		{
			get
			{
				return this._Create_User;
			}
			set
			{
				if ((this._Create_User != value))
				{
					this.OnCreate_UserChanging(value);
					this.SendPropertyChanging();
					this._Create_User = value;
					this.SendPropertyChanged("Create_User");
					this.OnCreate_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Create_Date
		{
			get
			{
				return this._Create_Date;
			}
			set
			{
				if ((this._Create_Date != value))
				{
					this.OnCreate_DateChanging(value);
					this.SendPropertyChanging();
					this._Create_Date = value;
					this.SendPropertyChanged("Create_Date");
					this.OnCreate_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_Description", DbType="VarChar(MAX)")]
		public string Full_Description
		{
			get
			{
				return this._Full_Description;
			}
			set
			{
				if ((this._Full_Description != value))
				{
					this.OnFull_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._Full_Description = value;
					this.SendPropertyChanged("Full_Description");
					this.OnFull_DescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Accounting_Consumer_InvoiceFee")]
	public partial class TBL_Accounting_Consumer_InvoiceFee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cons_Invoice_FeeId;
		
		private System.Nullable<int> _Cons_Invoice_Id;
		
		private System.Nullable<int> _FeeTypeId;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<System.DateTime> _DueDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCons_Invoice_FeeIdChanging(int value);
    partial void OnCons_Invoice_FeeIdChanged();
    partial void OnCons_Invoice_IdChanging(System.Nullable<int> value);
    partial void OnCons_Invoice_IdChanged();
    partial void OnFeeTypeIdChanging(System.Nullable<int> value);
    partial void OnFeeTypeIdChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnDueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDueDateChanged();
    #endregion
		
		public TBL_Accounting_Consumer_InvoiceFee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cons_Invoice_FeeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cons_Invoice_FeeId
		{
			get
			{
				return this._Cons_Invoice_FeeId;
			}
			set
			{
				if ((this._Cons_Invoice_FeeId != value))
				{
					this.OnCons_Invoice_FeeIdChanging(value);
					this.SendPropertyChanging();
					this._Cons_Invoice_FeeId = value;
					this.SendPropertyChanged("Cons_Invoice_FeeId");
					this.OnCons_Invoice_FeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cons_Invoice_Id", DbType="Int")]
		public System.Nullable<int> Cons_Invoice_Id
		{
			get
			{
				return this._Cons_Invoice_Id;
			}
			set
			{
				if ((this._Cons_Invoice_Id != value))
				{
					this.OnCons_Invoice_IdChanging(value);
					this.SendPropertyChanging();
					this._Cons_Invoice_Id = value;
					this.SendPropertyChanged("Cons_Invoice_Id");
					this.OnCons_Invoice_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeTypeId", DbType="Int")]
		public System.Nullable<int> FeeTypeId
		{
			get
			{
				return this._FeeTypeId;
			}
			set
			{
				if ((this._FeeTypeId != value))
				{
					this.OnFeeTypeIdChanging(value);
					this.SendPropertyChanging();
					this._FeeTypeId = value;
					this.SendPropertyChanged("FeeTypeId");
					this.OnFeeTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DueDate
		{
			get
			{
				return this._DueDate;
			}
			set
			{
				if ((this._DueDate != value))
				{
					this.OnDueDateChanging(value);
					this.SendPropertyChanging();
					this._DueDate = value;
					this.SendPropertyChanged("DueDate");
					this.OnDueDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Accounting_ConsumerInvoice")]
	public partial class TBL_Accounting_ConsumerInvoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cons_Invoice_Id;
		
		private string _Billto;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _InvoiceNumber;
		
		private string _Indicator;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCons_Invoice_IdChanging(int value);
    partial void OnCons_Invoice_IdChanged();
    partial void OnBilltoChanging(string value);
    partial void OnBilltoChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnInvoiceNumberChanging(string value);
    partial void OnInvoiceNumberChanged();
    partial void OnIndicatorChanging(string value);
    partial void OnIndicatorChanged();
    #endregion
		
		public TBL_Accounting_ConsumerInvoice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cons_Invoice_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cons_Invoice_Id
		{
			get
			{
				return this._Cons_Invoice_Id;
			}
			set
			{
				if ((this._Cons_Invoice_Id != value))
				{
					this.OnCons_Invoice_IdChanging(value);
					this.SendPropertyChanging();
					this._Cons_Invoice_Id = value;
					this.SendPropertyChanged("Cons_Invoice_Id");
					this.OnCons_Invoice_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Billto", DbType="VarChar(500)")]
		public string Billto
		{
			get
			{
				return this._Billto;
			}
			set
			{
				if ((this._Billto != value))
				{
					this.OnBilltoChanging(value);
					this.SendPropertyChanging();
					this._Billto = value;
					this.SendPropertyChanged("Billto");
					this.OnBilltoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(500)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(500)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(50)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="VarChar(50)")]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this.OnInvoiceNumberChanging(value);
					this.SendPropertyChanging();
					this._InvoiceNumber = value;
					this.SendPropertyChanged("InvoiceNumber");
					this.OnInvoiceNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indicator", DbType="VarChar(50)")]
		public string Indicator
		{
			get
			{
				return this._Indicator;
			}
			set
			{
				if ((this._Indicator != value))
				{
					this.OnIndicatorChanging(value);
					this.SendPropertyChanging();
					this._Indicator = value;
					this.SendPropertyChanged("Indicator");
					this.OnIndicatorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lkp_data")]
	public partial class tbl_lkp_data : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Lkp_data_ID;
		
		private int _Lkp_tbl_ID;
		
		private int _Org_ID;
		
		private string _Values;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLkp_data_IDChanging(int value);
    partial void OnLkp_data_IDChanged();
    partial void OnLkp_tbl_IDChanging(int value);
    partial void OnLkp_tbl_IDChanged();
    partial void OnOrg_IDChanging(int value);
    partial void OnOrg_IDChanged();
    partial void OnValuesChanging(string value);
    partial void OnValuesChanged();
    #endregion
		
		public tbl_lkp_data()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lkp_data_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Lkp_data_ID
		{
			get
			{
				return this._Lkp_data_ID;
			}
			set
			{
				if ((this._Lkp_data_ID != value))
				{
					this.OnLkp_data_IDChanging(value);
					this.SendPropertyChanging();
					this._Lkp_data_ID = value;
					this.SendPropertyChanged("Lkp_data_ID");
					this.OnLkp_data_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lkp_tbl_ID", DbType="Int NOT NULL")]
		public int Lkp_tbl_ID
		{
			get
			{
				return this._Lkp_tbl_ID;
			}
			set
			{
				if ((this._Lkp_tbl_ID != value))
				{
					this.OnLkp_tbl_IDChanging(value);
					this.SendPropertyChanging();
					this._Lkp_tbl_ID = value;
					this.SendPropertyChanged("Lkp_tbl_ID");
					this.OnLkp_tbl_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Org_ID", DbType="Int NOT NULL")]
		public int Org_ID
		{
			get
			{
				return this._Org_ID;
			}
			set
			{
				if ((this._Org_ID != value))
				{
					this.OnOrg_IDChanging(value);
					this.SendPropertyChanging();
					this._Org_ID = value;
					this.SendPropertyChanged("Org_ID");
					this.OnOrg_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Values]", Storage="_Values", DbType="VarChar(500)")]
		public string Values
		{
			get
			{
				return this._Values;
			}
			set
			{
				if ((this._Values != value))
				{
					this.OnValuesChanging(value);
					this.SendPropertyChanging();
					this._Values = value;
					this.SendPropertyChanged("Values");
					this.OnValuesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class USP_Accounting_GetFinancialBatchResultsResult
	{
		
		private int _Batch_ID;
		
		private string _Batchnum;
		
		private System.Nullable<int> _User_ID;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.DateTime> _ClosedDate;
		
		private string _UserName;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<int> _noftrans;
		
		public USP_Accounting_GetFinancialBatchResultsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Batch_ID", DbType="Int NOT NULL")]
		public int Batch_ID
		{
			get
			{
				return this._Batch_ID;
			}
			set
			{
				if ((this._Batch_ID != value))
				{
					this._Batch_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Batchnum", DbType="VarChar(50)")]
		public string Batchnum
		{
			get
			{
				return this._Batchnum;
			}
			set
			{
				if ((this._Batchnum != value))
				{
					this._Batchnum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="Int")]
		public System.Nullable<int> User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this._User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(500)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClosedDate
		{
			get
			{
				return this._ClosedDate;
			}
			set
			{
				if ((this._ClosedDate != value))
				{
					this._ClosedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noftrans", DbType="Int")]
		public System.Nullable<int> noftrans
		{
			get
			{
				return this._noftrans;
			}
			set
			{
				if ((this._noftrans != value))
				{
					this._noftrans = value;
				}
			}
		}
	}
	
	public partial class USP_Accounting_GetFinancialBatchTransforBatchNoResultsResult
	{
		
		private System.Nullable<int> _FeeID;
		
		private System.Nullable<int> _ReceiptID;
		
		private System.Nullable<int> _Receipt_ID;
		
		private System.Nullable<decimal> _Amount;
		
		private string _Receiptnum;
		
		private string _Checknum;
		
		private System.Nullable<int> _Person_ID;
		
		private string _PaymentType;
		
		private string _PayerID;
		
		private string _CCHolderName;
		
		private string _ReReceiptFrom;
		
		private string _ReReceiptTo;
		
		private string _ReceiptToName;
		
		private System.Nullable<int> _BatchStatus;
		
		public USP_Accounting_GetFinancialBatchTransforBatchNoResultsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeID", DbType="Int")]
		public System.Nullable<int> FeeID
		{
			get
			{
				return this._FeeID;
			}
			set
			{
				if ((this._FeeID != value))
				{
					this._FeeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptID", DbType="Int")]
		public System.Nullable<int> ReceiptID
		{
			get
			{
				return this._ReceiptID;
			}
			set
			{
				if ((this._ReceiptID != value))
				{
					this._ReceiptID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receipt_ID", DbType="Int")]
		public System.Nullable<int> Receipt_ID
		{
			get
			{
				return this._Receipt_ID;
			}
			set
			{
				if ((this._Receipt_ID != value))
				{
					this._Receipt_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receiptnum", DbType="VarChar(50)")]
		public string Receiptnum
		{
			get
			{
				return this._Receiptnum;
			}
			set
			{
				if ((this._Receiptnum != value))
				{
					this._Receiptnum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checknum", DbType="VarChar(50)")]
		public string Checknum
		{
			get
			{
				return this._Checknum;
			}
			set
			{
				if ((this._Checknum != value))
				{
					this._Checknum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Person_ID", DbType="Int")]
		public System.Nullable<int> Person_ID
		{
			get
			{
				return this._Person_ID;
			}
			set
			{
				if ((this._Person_ID != value))
				{
					this._Person_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentType", DbType="VarChar(500)")]
		public string PaymentType
		{
			get
			{
				return this._PaymentType;
			}
			set
			{
				if ((this._PaymentType != value))
				{
					this._PaymentType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayerID", DbType="VarChar(150)")]
		public string PayerID
		{
			get
			{
				return this._PayerID;
			}
			set
			{
				if ((this._PayerID != value))
				{
					this._PayerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCHolderName", DbType="VarChar(50)")]
		public string CCHolderName
		{
			get
			{
				return this._CCHolderName;
			}
			set
			{
				if ((this._CCHolderName != value))
				{
					this._CCHolderName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReReceiptFrom", DbType="VarChar(50)")]
		public string ReReceiptFrom
		{
			get
			{
				return this._ReReceiptFrom;
			}
			set
			{
				if ((this._ReReceiptFrom != value))
				{
					this._ReReceiptFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReReceiptTo", DbType="VarChar(50)")]
		public string ReReceiptTo
		{
			get
			{
				return this._ReReceiptTo;
			}
			set
			{
				if ((this._ReReceiptTo != value))
				{
					this._ReReceiptTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptToName", DbType="VarChar(152)")]
		public string ReceiptToName
		{
			get
			{
				return this._ReceiptToName;
			}
			set
			{
				if ((this._ReceiptToName != value))
				{
					this._ReceiptToName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatchStatus", DbType="Int")]
		public System.Nullable<int> BatchStatus
		{
			get
			{
				return this._BatchStatus;
			}
			set
			{
				if ((this._BatchStatus != value))
				{
					this._BatchStatus = value;
				}
			}
		}
	}
	
	public partial class usp_consumerInvoicerptResult
	{
		
		private string _Billto;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Indicator;
		
		private string _City;
		
		private string _cdt;
		
		private string _State;
		
		private string _Zip;
		
		private string _InvoiceNumber;
		
		public usp_consumerInvoicerptResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Billto", DbType="VarChar(500)")]
		public string Billto
		{
			get
			{
				return this._Billto;
			}
			set
			{
				if ((this._Billto != value))
				{
					this._Billto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(500)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(500)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indicator", DbType="VarChar(50)")]
		public string Indicator
		{
			get
			{
				return this._Indicator;
			}
			set
			{
				if ((this._Indicator != value))
				{
					this._Indicator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdt", DbType="VarChar(20)")]
		public string cdt
		{
			get
			{
				return this._cdt;
			}
			set
			{
				if ((this._cdt != value))
				{
					this._cdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(500)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(50)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this._Zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="VarChar(50)")]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
